---
name: prathamesh
on:
  workflow_dispatch: null
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from github"
  build:
    needs:
      - code
    runs-on: ubuntu-latest
    steps:
      - name: build docker container
        run: echo "docker container build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        run: echo " test the container"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy the app
        run: echo "docker compose deployed the app"
