name: prathamesh

on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to prathamesh
      - run : echo "hi prathamesh"
    
  show-versions: 
      runs-on: ubuntu-latest
      steps: 
        - name: show docker and python versions
        - run : docker --version && python --version
