name: Prathamesh

on:
    push:
        branches: [main]

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: say hello to users
            - run: echo "hello prathamesh"

            - name: show docker and python version
            - run: docker --version && python --version
